<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>template</ToolCommandName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NiceShell.Cli" Version="2026.106.104.1-template-101" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.CommandLine" />
    <Using Include="NiceShell" />
  </ItemGroup>

</Project>
