name: CliWrap Nuget (NiceShell.CliWrap)
on:
  push:
    paths:
      - 'cli-wrap/lib/**'
      - '.github/workflows/cli-wrap-nuget.yaml'
  workflow_dispatch:

jobs:
  publish:
    name: Pack & Publish nuget
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@main
        with:
          project: cli-wrap/lib/NiceShell.CliWrap
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}