name: NiceShell.Cli.Template Nuget
on:
  push:
    paths:
      - 'cli/**'
      - '.github/workflows/cli-template-nuget.yaml'
  workflow_dispatch:

jobs:
  publish:
    name: Pack & Publish nuget
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@main
        with:
          project: cli/NiceShell.Cli.Template
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}